name: xsrp
channels:
  - defaults
dependencies:
  - appdirs=1.4.4=pyhd3eb1b0_0
  - attrs=22.1.0=py39hca03da5_0
  - blas=1.0=openblas
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotlipy=0.7.0=py39h1a28f6b_1002
  - ca-certificates=2023.05.30=hca03da5_0
  - certifi=2023.5.7=py39hca03da5_0
  - cffi=1.15.1=py39h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py39h525c30c_0
  - cryptography=39.0.1=py39h834c97f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - exceptiongroup=1.0.4=py39hca03da5_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - giflib=5.2.1=h80987f9_3
  - idna=3.4=py39hca03da5_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - jpeg=9e=h80987f9_1
  - kiwisolver=1.4.4=py39h313beb8_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_0
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libtiff=4.5.0=h313beb8_2
  - libwebp=1.2.4=ha3663a8_1
  - libwebp-base=1.2.4=h80987f9_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - matplotlib=3.7.1=py39hca03da5_1
  - matplotlib-base=3.7.1=py39h78102c4_1
  - munkres=1.1.4=py_0
  - ncurses=6.4=h313beb8_0
  - numpy=1.25.0=py39h3b2db8e_0
  - numpy-base=1.25.0=py39ha9811e2_0
  - openssl=3.0.9=h1a28f6b_0
  - packaging=23.0=py39hca03da5_0
  - pillow=9.4.0=py39h313beb8_0
  - pip=23.1.2=py39hca03da5_0
  - pluggy=1.0.0=py39hca03da5_1
  - pooch=1.4.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py39hca03da5_0
  - pyparsing=3.0.9=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_0
  - pytest=7.3.1=py39hca03da5_0
  - python=3.9.17=hb885b13_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - readline=8.2=h1a28f6b_0
  - requests=2.29.0=py39hca03da5_0
  - scipy=1.10.1=py39h9d039d2_1
  - setuptools=67.8.0=py39hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h80987f9_0
  - tk=8.6.12=hb8d0fd4_0
  - tomli=2.0.1=py39hca03da5_0
  - tornado=6.2=py39h1a28f6b_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py39hca03da5_0
  - wheel=0.38.4=py39hca03da5_0
  - xz=5.4.2=h80987f9_0
  - zipp=3.11.0=py39hca03da5_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - cython==0.29.36
      - pybind11==2.10.4
      - pyroomacoustics==0.7.3
      - soundfile==0.12.1
prefix: /Users/ezajlerg/opt/anaconda3/envs/xsrp
